import { writeFile } from 'node:fs/promises';
import { parseFeaturedPlacements, parseSort } from './adapters.mjs';
import { resolveThumbnail } from './download-thumb.mjs';

function rowToSocialPost(row, thumbCdnBase) {
  const thumbnail = resolveThumbnail(row, thumbCdnBase);
  const excerpt = row.excerpt?.trim() || undefined;
  const likeRaw = row.like_count?.trim();
  const commentRaw = row.comment_count?.trim();
  const likeCount = likeRaw ? parseInt(likeRaw, 10) : undefined;
  const commentCount = commentRaw ? parseInt(commentRaw, 10) : undefined;
  const authorAvatar = row.author_avatar_cdn?.trim() || undefined;
  // Prefer real caption/title; never invent "@handle on platform" (redundant with author + badge).
  const title =
    row.title?.trim() ||
    excerpt?.slice(0, 80) ||
    row.scenario_tag?.trim() ||
    '';
  return {
    id: row.id.trim(),
    externalUrl: row.url.trim(),
    platform: row.platform.trim(),
    format: row.format.trim() === 'reel' ? 'reel' : 'post',
    product: row.product.trim(),
    author: row.author?.trim() || 'Unknown',
    title,
    excerpt,
    scenarioTag: row.scenario_tag?.trim() || undefined,
    language: row.language?.trim() || undefined,
    date: row.date?.trim() || undefined,
    featuredPlacements: parseFeaturedPlacements(row.featured_placements),
    sort: parseSort(row.sort),
    zIndex: parseSort(row.z_index),
    thumbnail,
    likeCount: Number.isNaN(likeCount) ? undefined : likeCount,
    commentCount: Number.isNaN(commentCount) ? undefined : commentCount,
    authorAvatar,
    fetchStatus: row.fetch_status?.trim() || 'pending',
  };
}

export async function generateSocialPostsTs(generatedTsPath, rows, thumbCdnBase) {
  const posts = rows
    .filter((row) => row.id?.trim() && row.url?.trim())
    .map((row) => rowToSocialPost(row, thumbCdnBase))
    .sort((a, b) => a.sort - b.sort || a.id.localeCompare(b.id));

  const ts = `// AUTO-GENERATED by sync-social-posts.mjs — do not edit manually
// generated: ${new Date().toISOString()}

import type { SocialPost } from '../lib/social-posts.ts';

export const socialPostsGeneratedAt = '${new Date().toISOString()}' as const;

export const socialPosts: SocialPost[] = ${JSON.stringify(posts, null, 2)} as SocialPost[];
`;

  await writeFile(generatedTsPath, ts, 'utf8');
  console.log(`✓ Wrote ${generatedTsPath} (${posts.length} posts)`);
  return posts;
}
