title: 製品
nav:
    - index.md
    - Mini-KVM:
        - minikvm/index.md
        - minikvm/箱の中身.md
        - minikvm/機能.md
        - ../app/基本.md
        - minikvm/接続方法.md
        - 仕組み: /faq/usbkvm/kvm-over-usb/
        - レビューとプレス: minikvm/reviews.md
        - minikvm/仕様.md
        - minikvm/USBスイッチ.md
        - minikvm/拡張ピン.md
        - よくある質問とトラブルシュート: /faq/minikvm/op-minikvm/
        - なぜOpenterfaceなのか: /faq/usbkvm/openterface/
    - Mini-KVM Lite (プレローンチ):
        - minikvm-lite/pre-launch.md
    - アクセサリー:
        - accessories/index.md
        - VGAからHDMIケーブル1m: accessories/vga-to-hdmi-cable.md
        - Type-C to Cケーブルナイロン1.5m: accessories/nylong-c-to-c-150.md
        - Type-C to Cケーブルオレンジ1.5m: accessories/type-c-to-c-cable-with-adapter.md
        - Type-C to Aケーブル黒30cm: accessories/black-c-to-a-30.md
        - HDMIケーブル30cm: accessories/hdmi-male-to-male-cable.md
        - ツールキットバッグ: accessories/openterface-toolkit-bag.md