authors:
  TechxArtisan:
    name: TechxArtisan Studio
    description: A creative studio and community of tech enthusiasts.
    avatar: /images/txa-avatar.jpg

  Openterface:
    name: Openterface
    description: Hi there!
    avatar: /images/op-avatar.jpg