authors:
  TechxArtisan:
    name: TechxArtisan
    description: 創造的なスタジオであり、テクノロジー愛好家のコミュニティです。
    avatar: /images/txa-avatar.jpg

  Openterface:
    name: Openterface
    description: こんにちは！
    avatar: /images/op-avatar.jpg