// AUTO-GENERATED by scripts/sync-home-videos.mjs — do not edit manually
// locale: ja | generated: 2026-05-29T06:25:45.959Z

import type { HomeVideo } from '../lib/youtube';

export const homeVideosLocale = 'ja' as const;

/** Top 10 videos for homepage strip (duplicated for seamless scroll). */
export const homeVideos: HomeVideo[] = [
  {
    "url": "https://www.youtube.com/watch?v=B7GHj7mPei4",
    "title": "【楽しすぎる】M4 MacMini 2024を外に持ち出す方法がロマンすぎた！！！！",
    "author": "野市 零 / Zero Noichi",
    "channelAvatar": "https://yt3.ggpht.com/-wFXaLYB_lhWD63lDMk7y9_ye3uBcM68c1Yh9B-_9iSQR5OxUwwiJBkzKrZasEe4_rEYVoLA=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/B7GHj7mPei4/hqdefault.jpg",
    "date": "2024-11-18",
    "views": 16012,
    "viewsFormatted": "16.0K"
  },
  {
    "url": "https://www.youtube.com/watch?v=1iTaDp24PBI",
    "title": "【革命】M4 MacMini 2024を外に持ち出して使えたwwww",
    "author": "野市 零 / Zero Noichi",
    "channelAvatar": "https://yt3.ggpht.com/-wFXaLYB_lhWD63lDMk7y9_ye3uBcM68c1Yh9B-_9iSQR5OxUwwiJBkzKrZasEe4_rEYVoLA=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/1iTaDp24PBI/hqdefault.jpg",
    "date": "2024-11-16",
    "views": 4566,
    "viewsFormatted": "4.6K"
  },
  {
    "url": "https://www.youtube.com/watch?v=U8kvzWnOWWc",
    "title": "【openterface Mini-KVM】ノートPCをサーバーなどのコンソールとして利用する機器のご紹介",
    "author": "N's on a trip",
    "channelAvatar": "https://yt3.ggpht.com/ytc/AIdro_mZcPSKP_AhotkMl-hIEgx1D4jYY8WrBMdilMfqR3lGhw=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/U8kvzWnOWWc/hqdefault.jpg",
    "date": "2024-08-24",
    "views": 4277,
    "viewsFormatted": "4.3K"
  },
  {
    "url": "https://www.youtube.com/watch?v=hOSP7je8zSk",
    "title": "【紹介】【スイッチ】【簡単】1社に1個あると良い！TechxArtisan社のMini KVM",
    "author": "もりこーぽちゃんねる　インフラ系エンジニア情報チャンネル",
    "channelAvatar": "https://yt3.ggpht.com/SnBBa_jP4nHBXxH8x15EVoxK0Lmd7DNUPaSIzajdyHLBylcN9DtqmK11YH5IDoTtpgprQUiBKt8=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/hOSP7je8zSk/hqdefault.jpg",
    "date": "2024-09-06",
    "views": 2715,
    "viewsFormatted": "2.7K"
  },
  {
    "url": "https://www.youtube.com/watch?v=URAXtrB817E",
    "title": "KVM-GO OpenInterface: Este KVM NO va por red, el KVM que se conecta DIRECTO a tu PC",
    "author": "Javier Gutierrez Abella",
    "channelAvatar": "https://yt3.ggpht.com/ytc/AIdro_lkVDRCHKSbjko5n0Vto1FazyoHLtYHZ0BJLq554iF0ZNW1=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/URAXtrB817E/hqdefault.jpg",
    "date": "2026-03-20",
    "views": 9549,
    "viewsFormatted": "9.5K"
  },
  {
    "url": "https://www.youtube.com/watch?v=JK4XaMo8yEI",
    "title": "A USB KVM with VGA! Openterface KVM-GO Review",
    "author": "apalrd's adventures",
    "channelAvatar": "https://yt3.ggpht.com/qencJ8YC4SCPbV_ylp47d-yNIAMTzt6QlncVrJ8FfwRDYeB4m7St7MZNSCDOVx3Qw_9CJxHR5A=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/JK4XaMo8yEI/hqdefault.jpg",
    "date": "2026-02-26",
    "views": 7828,
    "viewsFormatted": "7.8K"
  },
  {
    "url": "https://www.youtube.com/watch?v=BHRGIE8OGYY",
    "title": "Networkless KVM? Yes please open interface kvm-go",
    "author": "KL Tech Videos",
    "channelAvatar": "https://yt3.ggpht.com/mHmleJwkNJwBHMDRv-JXOxpitAiPG5YIsQ4uDApdTKjWu5mD_sUTfnH8VsL9Zwfcg5PKivTQ7Q=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/BHRGIE8OGYY/hqdefault.jpg",
    "date": "2025-12-31",
    "views": 717,
    "viewsFormatted": "717"
  },
  {
    "url": "https://www.youtube.com/watch?v=d9-i7SYAZr8",
    "title": "The KVM-GO is my new EDC KVM!",
    "author": "Symbiiote",
    "channelAvatar": "https://yt3.ggpht.com/OYi4mIbKHArwGmdur42okpmZ3VMRJlMixLH2YOvgv2EqWzzvxx1wgwh0RugCBjTuYAVGne4B=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/d9-i7SYAZr8/hqdefault.jpg",
    "date": "2025-12-29",
    "views": 1505,
    "viewsFormatted": "1.5K"
  },
  {
    "url": "https://www.youtube.com/watch?v=aXQSNFAFiqk",
    "title": "J’ai testé le KVM le plus compact au monde : OpenTerface KVM Go !",
    "author": "Sam's eXperiments logs",
    "channelAvatar": "https://yt3.ggpht.com/QypC0fMJdJDxdf_04lp6TWkuorFPB9pVZD8oOLwclsvRfJsfzCz01iaSl56A1J9lcCHUHXEM=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/aXQSNFAFiqk/hqdefault.jpg",
    "date": "2025-12-16",
    "views": 357,
    "viewsFormatted": "357"
  },
  {
    "url": "https://www.youtube.com/watch?v=__WfaaAS0O4",
    "title": "OpenInterface Shows New KVM Go at Maker Faire Shenzhen",
    "author": "Electromaker",
    "channelAvatar": "https://yt3.ggpht.com/erBuQrc8PUPxL6UVWNLwUUXZu1QoY1qmWe4x-nVdxhw_kMOeMsT3SDhHM3sYxt2oYKC--zNvug=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/__WfaaAS0O4/hqdefault.jpg",
    "date": "2025-11-21",
    "views": 6730,
    "viewsFormatted": "6.7K"
  },
  {
    "url": "https://www.youtube.com/watch?v=B7GHj7mPei4",
    "title": "【楽しすぎる】M4 MacMini 2024を外に持ち出す方法がロマンすぎた！！！！",
    "author": "野市 零 / Zero Noichi",
    "channelAvatar": "https://yt3.ggpht.com/-wFXaLYB_lhWD63lDMk7y9_ye3uBcM68c1Yh9B-_9iSQR5OxUwwiJBkzKrZasEe4_rEYVoLA=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/B7GHj7mPei4/hqdefault.jpg",
    "date": "2024-11-18",
    "views": 16012,
    "viewsFormatted": "16.0K"
  },
  {
    "url": "https://www.youtube.com/watch?v=1iTaDp24PBI",
    "title": "【革命】M4 MacMini 2024を外に持ち出して使えたwwww",
    "author": "野市 零 / Zero Noichi",
    "channelAvatar": "https://yt3.ggpht.com/-wFXaLYB_lhWD63lDMk7y9_ye3uBcM68c1Yh9B-_9iSQR5OxUwwiJBkzKrZasEe4_rEYVoLA=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/1iTaDp24PBI/hqdefault.jpg",
    "date": "2024-11-16",
    "views": 4566,
    "viewsFormatted": "4.6K"
  },
  {
    "url": "https://www.youtube.com/watch?v=U8kvzWnOWWc",
    "title": "【openterface Mini-KVM】ノートPCをサーバーなどのコンソールとして利用する機器のご紹介",
    "author": "N's on a trip",
    "channelAvatar": "https://yt3.ggpht.com/ytc/AIdro_mZcPSKP_AhotkMl-hIEgx1D4jYY8WrBMdilMfqR3lGhw=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/U8kvzWnOWWc/hqdefault.jpg",
    "date": "2024-08-24",
    "views": 4277,
    "viewsFormatted": "4.3K"
  },
  {
    "url": "https://www.youtube.com/watch?v=hOSP7je8zSk",
    "title": "【紹介】【スイッチ】【簡単】1社に1個あると良い！TechxArtisan社のMini KVM",
    "author": "もりこーぽちゃんねる　インフラ系エンジニア情報チャンネル",
    "channelAvatar": "https://yt3.ggpht.com/SnBBa_jP4nHBXxH8x15EVoxK0Lmd7DNUPaSIzajdyHLBylcN9DtqmK11YH5IDoTtpgprQUiBKt8=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/hOSP7je8zSk/hqdefault.jpg",
    "date": "2024-09-06",
    "views": 2715,
    "viewsFormatted": "2.7K"
  },
  {
    "url": "https://www.youtube.com/watch?v=URAXtrB817E",
    "title": "KVM-GO OpenInterface: Este KVM NO va por red, el KVM que se conecta DIRECTO a tu PC",
    "author": "Javier Gutierrez Abella",
    "channelAvatar": "https://yt3.ggpht.com/ytc/AIdro_lkVDRCHKSbjko5n0Vto1FazyoHLtYHZ0BJLq554iF0ZNW1=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/URAXtrB817E/hqdefault.jpg",
    "date": "2026-03-20",
    "views": 9549,
    "viewsFormatted": "9.5K"
  },
  {
    "url": "https://www.youtube.com/watch?v=JK4XaMo8yEI",
    "title": "A USB KVM with VGA! Openterface KVM-GO Review",
    "author": "apalrd's adventures",
    "channelAvatar": "https://yt3.ggpht.com/qencJ8YC4SCPbV_ylp47d-yNIAMTzt6QlncVrJ8FfwRDYeB4m7St7MZNSCDOVx3Qw_9CJxHR5A=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/JK4XaMo8yEI/hqdefault.jpg",
    "date": "2026-02-26",
    "views": 7828,
    "viewsFormatted": "7.8K"
  },
  {
    "url": "https://www.youtube.com/watch?v=BHRGIE8OGYY",
    "title": "Networkless KVM? Yes please open interface kvm-go",
    "author": "KL Tech Videos",
    "channelAvatar": "https://yt3.ggpht.com/mHmleJwkNJwBHMDRv-JXOxpitAiPG5YIsQ4uDApdTKjWu5mD_sUTfnH8VsL9Zwfcg5PKivTQ7Q=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/BHRGIE8OGYY/hqdefault.jpg",
    "date": "2025-12-31",
    "views": 717,
    "viewsFormatted": "717"
  },
  {
    "url": "https://www.youtube.com/watch?v=d9-i7SYAZr8",
    "title": "The KVM-GO is my new EDC KVM!",
    "author": "Symbiiote",
    "channelAvatar": "https://yt3.ggpht.com/OYi4mIbKHArwGmdur42okpmZ3VMRJlMixLH2YOvgv2EqWzzvxx1wgwh0RugCBjTuYAVGne4B=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/d9-i7SYAZr8/hqdefault.jpg",
    "date": "2025-12-29",
    "views": 1505,
    "viewsFormatted": "1.5K"
  },
  {
    "url": "https://www.youtube.com/watch?v=aXQSNFAFiqk",
    "title": "J’ai testé le KVM le plus compact au monde : OpenTerface KVM Go !",
    "author": "Sam's eXperiments logs",
    "channelAvatar": "https://yt3.ggpht.com/QypC0fMJdJDxdf_04lp6TWkuorFPB9pVZD8oOLwclsvRfJsfzCz01iaSl56A1J9lcCHUHXEM=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/aXQSNFAFiqk/hqdefault.jpg",
    "date": "2025-12-16",
    "views": 357,
    "viewsFormatted": "357"
  },
  {
    "url": "https://www.youtube.com/watch?v=__WfaaAS0O4",
    "title": "OpenInterface Shows New KVM Go at Maker Faire Shenzhen",
    "author": "Electromaker",
    "channelAvatar": "https://yt3.ggpht.com/erBuQrc8PUPxL6UVWNLwUUXZu1QoY1qmWe4x-nVdxhw_kMOeMsT3SDhHM3sYxt2oYKC--zNvug=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/__WfaaAS0O4/hqdefault.jpg",
    "date": "2025-11-21",
    "views": 6730,
    "viewsFormatted": "6.7K"
  }
] as HomeVideo[];
