// AUTO-GENERATED by scripts/sync-home-videos.mjs — do not edit manually
// locale: ja | generated: 2026-09-10T10:00:08.385Z

import type { HomeVideo } from '../lib/youtube';

export const homeVideosLocale = 'ja' as const;

/** Top 10 videos for homepage strip (duplicated for seamless scroll). */
export const homeVideos: HomeVideo[] = [
  {
    "url": "https://www.youtube.com/watch?v=B7GHj7mPei4",
    "title": "【楽しすぎる】M4 MacMini 2024を外に持ち出す方法がロマンすぎた！！！！",
    "author": "野市 零 / Zero Noichi",
    "channelAvatar": "https://yt3.ggpht.com/-wFXaLYB_lhWD63lDMk7y9_ye3uBcM68c1Yh9B-_9iSQR5OxUwwiJBkzKrZasEe4_rEYVoLA=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/B7GHj7mPei4/hqdefault.jpg",
    "date": "2024-11-18",
    "views": 16012,
    "viewsFormatted": "16.0K"
  },
  {
    "url": "https://www.youtube.com/watch?v=1iTaDp24PBI",
    "title": "【革命】M4 MacMini 2024を外に持ち出して使えたwwww",
    "author": "野市 零 / Zero Noichi",
    "channelAvatar": "https://yt3.ggpht.com/-wFXaLYB_lhWD63lDMk7y9_ye3uBcM68c1Yh9B-_9iSQR5OxUwwiJBkzKrZasEe4_rEYVoLA=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/1iTaDp24PBI/hqdefault.jpg",
    "date": "2024-11-16",
    "views": 4566,
    "viewsFormatted": "4.6K"
  },
  {
    "url": "https://www.youtube.com/watch?v=U8kvzWnOWWc",
    "title": "【openterface Mini-KVM】ノートPCをサーバーなどのコンソールとして利用する機器のご紹介",
    "author": "N's on a trip",
    "channelAvatar": "https://yt3.ggpht.com/ytc/AIdro_mZcPSKP_AhotkMl-hIEgx1D4jYY8WrBMdilMfqR3lGhw=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/U8kvzWnOWWc/hqdefault.jpg",
    "date": "2024-08-24",
    "views": 4277,
    "viewsFormatted": "4.3K"
  },
  {
    "url": "https://www.youtube.com/watch?v=hOSP7je8zSk",
    "title": "【紹介】【スイッチ】【簡単】1社に1個あると良い！TechxArtisan社のMini KVM",
    "author": "もりこーぽちゃんねる　インフラ系エンジニア情報チャンネル",
    "channelAvatar": "https://yt3.ggpht.com/SnBBa_jP4nHBXxH8x15EVoxK0Lmd7DNUPaSIzajdyHLBylcN9DtqmK11YH5IDoTtpgprQUiBKt8=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/hOSP7je8zSk/hqdefault.jpg",
    "date": "2024-09-06",
    "views": 2715,
    "viewsFormatted": "2.7K"
  },
  {
    "url": "https://www.youtube.com/watch?v=Z7yiAT52_Ew",
    "title": "Openterface uConsole KVM Ext Module V2",
    "author": "RGhandhelds",
    "channelAvatar": "https://yt3.ggpht.com/_fe-uRZnAvnaYwrIWZbCP7t3cLC39MNVMqD2-OzXpwnejdTVTz5F2zYT4EekyvKeeD-2bjLhbg=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/Z7yiAT52_Ew/hqdefault.jpg",
    "date": "2026-08-15",
    "views": 248,
    "viewsFormatted": "248"
  },
  {
    "url": "https://www.youtube.com/watch?v=MydkuIGCO3o",
    "title": "Openterface KeyMod: Full Keyboard and Mouse in Your Pocket",
    "author": "Sam's eXperiments logs",
    "channelAvatar": "https://yt3.ggpht.com/QypC0fMJdJDxdf_04lp6TWkuorFPB9pVZD8oOLwclsvRfJsfzCz01iaSl56A1J9lcCHUHXEM=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/MydkuIGCO3o/hqdefault.jpg",
    "date": "2026-08-19",
    "views": 40,
    "viewsFormatted": "40"
  },
  {
    "url": "https://www.youtube.com/watch?v=zrJYZlWuuHE",
    "title": "Openterface KeyMod — Your Phone as Keyboard, Mouse, Terminal & Gamepad",
    "author": "Crowd Supply",
    "channelAvatar": "https://yt3.ggpht.com/bAUL0NBNgStzCx6LTGQRSoHFg4MMLYWp3w8W7RJejnh5-vIlTZwBBGOCmPFyS7JVtl8qY4C0=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/zrJYZlWuuHE/hqdefault.jpg",
    "date": "2026-08-19",
    "views": 4,
    "viewsFormatted": "4"
  },
  {
    "url": "https://www.youtube.com/watch?v=nl24-rPjOr8",
    "title": "Beta Testing The Openterface Keymod #keymod #openterface",
    "author": "Valleytech Custom Solutions",
    "channelAvatar": "https://yt3.ggpht.com/ZBz7pGNOU1PD-u6cEKWT6q0GKeep5Gh1pTHprSKHQhmHTZQGba71IoCUkQGrzwZSNW2rt8DMQg=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/nl24-rPjOr8/hqdefault.jpg",
    "date": "2026-06-05",
    "views": 19232,
    "viewsFormatted": "19.2K"
  },
  {
    "url": "https://www.youtube.com/watch?v=uq0F1VKmQdU",
    "title": "USB KVM that You Can Put on a Keychain | Openterface KVM-GO",
    "author": "Home Network Guy",
    "channelAvatar": "https://yt3.ggpht.com/wmQPGuau8ThNtsGR0Kc6m78_55P0_hH6fB4p2dPwHlIXyZ61SGk7yl9ogIMxaWhb8Q0f8zAn=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/uq0F1VKmQdU/hqdefault.jpg",
    "date": "2026-06-06",
    "views": 1875,
    "viewsFormatted": "1.9K"
  },
  {
    "url": "https://www.youtube.com/watch?v=x35Qs89WP_g",
    "title": "Openterface Keymod - Control Any Device with Your Phone",
    "author": "Valleytech Custom Solutions",
    "channelAvatar": "https://yt3.ggpht.com/ZBz7pGNOU1PD-u6cEKWT6q0GKeep5Gh1pTHprSKHQhmHTZQGba71IoCUkQGrzwZSNW2rt8DMQg=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/x35Qs89WP_g/hqdefault.jpg",
    "date": "2026-07-13",
    "views": 3222,
    "viewsFormatted": "3.2K"
  },
  {
    "url": "https://www.youtube.com/watch?v=B7GHj7mPei4",
    "title": "【楽しすぎる】M4 MacMini 2024を外に持ち出す方法がロマンすぎた！！！！",
    "author": "野市 零 / Zero Noichi",
    "channelAvatar": "https://yt3.ggpht.com/-wFXaLYB_lhWD63lDMk7y9_ye3uBcM68c1Yh9B-_9iSQR5OxUwwiJBkzKrZasEe4_rEYVoLA=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/B7GHj7mPei4/hqdefault.jpg",
    "date": "2024-11-18",
    "views": 16012,
    "viewsFormatted": "16.0K"
  },
  {
    "url": "https://www.youtube.com/watch?v=1iTaDp24PBI",
    "title": "【革命】M4 MacMini 2024を外に持ち出して使えたwwww",
    "author": "野市 零 / Zero Noichi",
    "channelAvatar": "https://yt3.ggpht.com/-wFXaLYB_lhWD63lDMk7y9_ye3uBcM68c1Yh9B-_9iSQR5OxUwwiJBkzKrZasEe4_rEYVoLA=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/1iTaDp24PBI/hqdefault.jpg",
    "date": "2024-11-16",
    "views": 4566,
    "viewsFormatted": "4.6K"
  },
  {
    "url": "https://www.youtube.com/watch?v=U8kvzWnOWWc",
    "title": "【openterface Mini-KVM】ノートPCをサーバーなどのコンソールとして利用する機器のご紹介",
    "author": "N's on a trip",
    "channelAvatar": "https://yt3.ggpht.com/ytc/AIdro_mZcPSKP_AhotkMl-hIEgx1D4jYY8WrBMdilMfqR3lGhw=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/U8kvzWnOWWc/hqdefault.jpg",
    "date": "2024-08-24",
    "views": 4277,
    "viewsFormatted": "4.3K"
  },
  {
    "url": "https://www.youtube.com/watch?v=hOSP7je8zSk",
    "title": "【紹介】【スイッチ】【簡単】1社に1個あると良い！TechxArtisan社のMini KVM",
    "author": "もりこーぽちゃんねる　インフラ系エンジニア情報チャンネル",
    "channelAvatar": "https://yt3.ggpht.com/SnBBa_jP4nHBXxH8x15EVoxK0Lmd7DNUPaSIzajdyHLBylcN9DtqmK11YH5IDoTtpgprQUiBKt8=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/hOSP7je8zSk/hqdefault.jpg",
    "date": "2024-09-06",
    "views": 2715,
    "viewsFormatted": "2.7K"
  },
  {
    "url": "https://www.youtube.com/watch?v=Z7yiAT52_Ew",
    "title": "Openterface uConsole KVM Ext Module V2",
    "author": "RGhandhelds",
    "channelAvatar": "https://yt3.ggpht.com/_fe-uRZnAvnaYwrIWZbCP7t3cLC39MNVMqD2-OzXpwnejdTVTz5F2zYT4EekyvKeeD-2bjLhbg=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/Z7yiAT52_Ew/hqdefault.jpg",
    "date": "2026-08-15",
    "views": 248,
    "viewsFormatted": "248"
  },
  {
    "url": "https://www.youtube.com/watch?v=MydkuIGCO3o",
    "title": "Openterface KeyMod: Full Keyboard and Mouse in Your Pocket",
    "author": "Sam's eXperiments logs",
    "channelAvatar": "https://yt3.ggpht.com/QypC0fMJdJDxdf_04lp6TWkuorFPB9pVZD8oOLwclsvRfJsfzCz01iaSl56A1J9lcCHUHXEM=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/MydkuIGCO3o/hqdefault.jpg",
    "date": "2026-08-19",
    "views": 40,
    "viewsFormatted": "40"
  },
  {
    "url": "https://www.youtube.com/watch?v=zrJYZlWuuHE",
    "title": "Openterface KeyMod — Your Phone as Keyboard, Mouse, Terminal & Gamepad",
    "author": "Crowd Supply",
    "channelAvatar": "https://yt3.ggpht.com/bAUL0NBNgStzCx6LTGQRSoHFg4MMLYWp3w8W7RJejnh5-vIlTZwBBGOCmPFyS7JVtl8qY4C0=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/zrJYZlWuuHE/hqdefault.jpg",
    "date": "2026-08-19",
    "views": 4,
    "viewsFormatted": "4"
  },
  {
    "url": "https://www.youtube.com/watch?v=nl24-rPjOr8",
    "title": "Beta Testing The Openterface Keymod #keymod #openterface",
    "author": "Valleytech Custom Solutions",
    "channelAvatar": "https://yt3.ggpht.com/ZBz7pGNOU1PD-u6cEKWT6q0GKeep5Gh1pTHprSKHQhmHTZQGba71IoCUkQGrzwZSNW2rt8DMQg=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/nl24-rPjOr8/hqdefault.jpg",
    "date": "2026-06-05",
    "views": 19232,
    "viewsFormatted": "19.2K"
  },
  {
    "url": "https://www.youtube.com/watch?v=uq0F1VKmQdU",
    "title": "USB KVM that You Can Put on a Keychain | Openterface KVM-GO",
    "author": "Home Network Guy",
    "channelAvatar": "https://yt3.ggpht.com/wmQPGuau8ThNtsGR0Kc6m78_55P0_hH6fB4p2dPwHlIXyZ61SGk7yl9ogIMxaWhb8Q0f8zAn=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/uq0F1VKmQdU/hqdefault.jpg",
    "date": "2026-06-06",
    "views": 1875,
    "viewsFormatted": "1.9K"
  },
  {
    "url": "https://www.youtube.com/watch?v=x35Qs89WP_g",
    "title": "Openterface Keymod - Control Any Device with Your Phone",
    "author": "Valleytech Custom Solutions",
    "channelAvatar": "https://yt3.ggpht.com/ZBz7pGNOU1PD-u6cEKWT6q0GKeep5Gh1pTHprSKHQhmHTZQGba71IoCUkQGrzwZSNW2rt8DMQg=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/x35Qs89WP_g/hqdefault.jpg",
    "date": "2026-07-13",
    "views": 3222,
    "viewsFormatted": "3.2K"
  }
] as HomeVideo[];
