/** Auto-generated by scripts/generate-keymod-agent-demo.mjs — do not edit by hand. */

export type AgentPlanStepKind = 'terminal' | 'macro' | 'hid';

export type AgentPlanStep = {
  index: number;
  title: string;
  subtitle: string;
  kind: AgentPlanStepKind;
};

export type AgentDemoScript = {
  id: string;
  pickerTitle: string;
  pickerTagline: string;
  userPrompt: string;
  assistantIntro: string;
  planSteps: AgentPlanStep[];
  summaryMessage: string;
  terminalOutputLines: string[];
  macroChecklist: string[];
  macroStatusChips: string[];
  hasCliExecution: boolean;
  hasMacroExecution: boolean;
};

export const AGENT_DEMO_TIMING = {
  beatDelayMs: 700,
  terminalLineDelayMs: 450,
  macroStepDelayMs: 650,
  autoStartDelayMs: 2500,
  completeHoldMs: 8000,
  intersectionThreshold: 0.35,
} as const;

export const AGENT_DEMO_DEFAULT_SCRIPT_ID = 'hero_mixed';

export const AGENT_DEMO_SCRIPTS: AgentDemoScript[] = [
  {
    "id": "hero_mixed",
    "pickerTitle": "Full workflow",
    "pickerTagline": "CLI + Macro in one command",
    "userPrompt": "Check disk space on the Mac, then run my Morning Setup macro.",
    "assistantIntro": "I'll connect to your Mac via Terminal, check disk usage, then play your Morning Setup macro on the host.",
    "planSteps": [
      {
        "index": 1,
        "title": "Connect SSH to target Mac",
        "subtitle": "~2s",
        "kind": "terminal"
      },
      {
        "index": 2,
        "title": "Run df -h /",
        "subtitle": "Check disk usage",
        "kind": "terminal"
      },
      {
        "index": 3,
        "title": "Play macro \"Morning Setup\"",
        "subtitle": "12 HID steps · ~8s",
        "kind": "macro"
      }
    ],
    "summaryMessage": "Done. Macintosh HD is 42% full. Morning Setup completed in 8s.",
    "terminalOutputLines": [
      "$ ssh mac-host",
      "Connecting to mac-host...",
      "Connected.",
      "$ df -h /",
      "Filesystem      Size   Used  Avail Capacity  Mounted on",
      "/dev/disk1s1   460Gi  193Gi  267Gi    42%    /",
      "Macintosh HD   42% used"
    ],
    "macroChecklist": [
      "Focus host window",
      "Open Finder",
      "Launch Safari",
      "Open calendar",
      "Dismiss notifications"
    ],
    "macroStatusChips": [
      "Sending <CMD>+<TAB>…",
      "Sending <CMD>+<SPACE>…",
      "Click Dock · Safari",
      "Sending <CMD>+<SPACE>…",
      "Sending <ESC>…"
    ],
    "hasCliExecution": true,
    "hasMacroExecution": true
  },
  {
    "id": "cli_only",
    "pickerTitle": "Terminal only",
    "pickerTagline": "Remote hands over SSH",
    "userPrompt": "What's using the most CPU on the Linux box?",
    "assistantIntro": "I'll SSH in and run top -bn1 sorted by CPU.",
    "planSteps": [
      {
        "index": 1,
        "title": "SSH to 192.168.50.10",
        "subtitle": "Linux host",
        "kind": "terminal"
      },
      {
        "index": 2,
        "title": "Run top -bn1 | head -20",
        "subtitle": "Sort by CPU",
        "kind": "terminal"
      }
    ],
    "summaryMessage": "Top consumer: nginx at 12.4% CPU. Want me to restart the service?",
    "terminalOutputLines": [
      "$ ssh user@192.168.50.10",
      "Connected to 192.168.50.10.",
      "$ top -bn1 | head -20",
      "  PID USER      PR  NI    VIRT    RES  %CPU  COMMAND",
      "  842 root      20   0  169032   4120  12.4  nginx",
      "  615 root      20   0   89312   3104   4.1  systemd",
      " 1204 node      20   0  512000  88400   3.2  node"
    ],
    "macroChecklist": [],
    "macroStatusChips": [],
    "hasCliExecution": true,
    "hasMacroExecution": false
  },
  {
    "id": "macro_only",
    "pickerTitle": "Macro only",
    "pickerTagline": "One phrase, full desktop workflow",
    "userPrompt": "Start my stream setup.",
    "assistantIntro": "I'll run your Stream Setup macro: 8 HID steps on the host.",
    "planSteps": [
      {
        "index": 1,
        "title": "Focus host window",
        "subtitle": "Bring target to front",
        "kind": "hid"
      },
      {
        "index": 2,
        "title": "Play macro \"Stream Setup\"",
        "subtitle": "8 HID steps · ~6s",
        "kind": "macro"
      }
    ],
    "summaryMessage": "Stream Setup finished. OBS is on scene \"Main\".",
    "terminalOutputLines": [],
    "macroChecklist": [
      "Focus host window",
      "Open Spotlight",
      "Launch OBS",
      "Select scene Main",
      "Start virtual camera"
    ],
    "macroStatusChips": [
      "Sending <CMD>+<TAB>…",
      "Sending <CMD>+<SPACE>…",
      "Typing OBS…",
      "Click scene Main",
      "Sending <CMD>+<SHIFT>+V…"
    ],
    "hasCliExecution": false,
    "hasMacroExecution": true
  }
];

export const AGENT_DEMO_SCRIPT_BY_ID: Record<string, AgentDemoScript> = Object.fromEntries(
  AGENT_DEMO_SCRIPTS.map((s) => [s.id, s]),
);
